---
title: "Data Viz 101"
subtitle: "Initiation à la datavizualisation en Python"
author: "Léo Mignot & Mickael Temporão"
date: "2026-01-08"
#format: pptx
format: 
    revealjs:
        scrollable: true
        slideNumber: true
        embed-resources: true
        theme: default
    # default
    # beige
    # blood
    # dark
    # default
    # dracula
    # league
    # moon
    # night
    # serif
    # simple
    # sky
    # solarized

---

## Éléments de contexte

---

## Pourquoi : but why 
- exemple meme : Datasaurus
- des graph crimes
- 
---

## Tour de table


---

## Organisation du cours
- passer directement le syllabus en revue
- ou détailler en quelques slides qui reprennent le syllabus (ex dessous)

---

## Objectifs de ce cours :

À la fin du semestre, vous saurez :

- **Concevoir** et **produire** des graphiques pour vos projets.
- Réaliser les **étapes clés** d'un projet de visualisation : chargement, préparation, analyse, et production graphique.
- **Choisir** un **type** de visualisation pertinent selon les données et le message que vous souhaitez véhiculer.
- Mobiliser des bibliothèques **Python** devenues incontournables en data visualisation.

---

## Format du cours et programme

- Format **atelier**
- Dimension **pratique**, avec des temps d'application et exercices sur des cas concrets.

Le module est organisé en séquences progressives :

- (1) installation de l’environnement de travail,
- (2) introduction au traitement et la manipulation de données,
- (3) réalisation de différents types de visualisations.

---

## Bloc 1 – Mise en place & premiers pas (2 séances)  
*Objectif : permettre à chacun·e de disposer d’un environnement de travail fonctionnel*

- Présentation du cours et des attendus
- Installation des environnements de développement (VS Code ou Google Colab) et prise en main
- Exécution d’une première visualisation à partir d'un code fourni par les enseignants

---

## Bloc 2 – Initiation à Python et à Pandas (4 séances)  
*Objectif : acquérir les bases de la programmation et du traitement de données*

- Syntaxe de base en Python
- Introduction à Pandas : chargement de bases, nettoyage, recodage, analyse
- Manipulation de variables et statistiques descriptives
- Préparation des données pour la visualisation

---

## Bloc 3 – Visualisation de données (6 séances)  
*Objectif : maîtriser les grands types de visualisation selon la nature des variables*

- Visualisations univariées : histogrammes, barplots, boxplots
- Visualisations bivariées : scatterplots, courbes, boxplots croisés
- Visualisations cartographiques : initiation à la visualisation spatiale (hexbin maps, cartes choroplèthes)

---

## Évaluation : modalités et attendus

- Approche incrémentale
- Remise de (petits) rendus intermédiaires
- Les rendus débouchent sur un rendu final prenant la forme d'une infographie aboutie.
- Travail en groupe

---

## Les rendus

| Date rendu         | Évaluation                                                              | Poids | Description                                                                 |
|--------------------|-------------------------------------------------------------------------|-------|-----------------------------------------------------------------------------|
| Séance 5           | Modifications de titres/sous-titres                                     | 10%   | Capacité à choisir des éléments éditoriaux clairs et pertinents             |
| Séance 7           | Identification de deux variables et calcul de statistiques descriptives | 10%   | Rigueur dans le choix des variables et la qualité du traitement             |
| Séance 9           | Prototype de visualisation univariée                                    | 10%   | Pertinence du graphique et lisibilité                                       |
| Séance 11          | Prototype de visualisation bivariée                                     | 10%   | Pertinence du graphique et lisibilité                                       |
| Final (10 avril)   | Figure finale                                                           | 60%   | Une visualisation aboutie, respectant tous les critères de qualité attendus |

---

## Outils
- Python
- Altair
- ajouter lien doc
- dire un mot de python et pourquoi python ?
- sans doute plutôt garder pour la prochaine séance selon timing ?

---

## Ressources
Plein, vues plus tard, mais notamment :

- truc
- bidule
- chose
- et la liste ici : lien biblio syllabus git ?

---

## Suck at something
- meme qui aime code are they in the room ?
- meme more bugs ?
- slide Nota bene : je code comme une brouette
- nous (enseignants) aussi on sera nul : on fait le pari de découvrir et apprendre la bibliothèque alatair 
- = ce qu'on évoquait sur se mettre au même niveau, dire que l'échec fait partie du jeu côté code
- et idée qui est aussi présente dans le cours d'andrewheiss https://datavizs25.classes.andrewheiss.com/slides/01-slides.html#58